# Name:        pr-test-and-build.yaml
# Author:      Mathew Fleisch <mathew.fleisch@gmail.com>
# Description: This action will run go lint/unit tests as well as
#              build a docker container and test it against a KinD cluster.
#              See Makefile for more details.
name: PR CI
on:
  pull_request:
    branches:
      - main

jobs:
  unit_test:
    name: Lint and Unit Tests
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - 
        name: Install stuff with asdf
        uses: asdf-vm/actions/install@v1
        with:
          tool_versions: |
            action-validator 0.1.2
            dockle 0.4.5
            helm 3.8.1
            yq 4.22.1
      -
        name: Lint Actions
        run: make lint-actions
      -
        name: Lint Helm Chart
        run: make helm-lint
      # -
      #   name: Lint Container Using Dockle
      #   env:
      #     DOCKER_CONTENT_TRUST: 1
      #   run: |
      #     make docker-build
      #     make docker-lint

  integration_test:
    name: KinD Integration Tests
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - 
        name: Install stuff with asdf
        uses: asdf-vm/actions/install@v1
        with:
          tool_versions: |
            helm 3.8.1
            yq 4.22.1
      -
        name: KinD Tests
        run: |
          make kind-test
          make kind-cleanup
      -
        name: Anchor Container Scan
        uses: anchore/scan-action@main
        with:
          image: "discord-loudbot:local"
          fail-build: false
          acs-report-enable: true
      -
        name: Upload Anchore Scan Report
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.sarif

